### ISSUE TITLE
not working for gradle 7+

### ISSUE THREAD

**Issue by kirbi96** [GennadySX/react-native-appmetrica#1]
for working change in build.gradle
// classpath += files(project.getConfigurations().getByName('compile').asList())
 classpath += files(project.getConfigurations().getByName('releaseCompileClasspath').asList())

and change
//    task installArchives(type: Upload) {
//        configuration = configurations.archives
//        repositories.mavenDeployer {
//            // Deploy to react-native-event-bridge/maven, ready to publish to npm
//            repository url: "file://${projectDir}/../android/maven"
//            configureReactNativePom pom
//        }
//    }

 publishing {
   publications {
        maven(MavenPublication) {
              artifact androidSourcesJar
          }
      }
 }

**Comment by GennadySX** [comment]
thank you for your notice!

They will be fixed soon!

**Comment by GennadySX** [comment]
checked and fixed!)
