### ISSUE TITLE
After upgrading version of react-native to 0.72.0 version yarn run android shows error in @gennadysx/react-native-appmetrica

### ISSUE THREAD

**Issue by itsmeshusha** [GennadySX/react-native-appmetrica#6]
error Failed to install the app. Command failed with exit code 1: ./gradlew tasks FAILURE: Build failed with an exception.

What went wrong:
A problem occurred configuring project ':gennadysx_react-native-appmetrica'.
Could not set unknown property 'classifier' for task ':gennadysx_react-native-appmetrica:androidJavadocJar' of type org.gradle.api.tasks.bundling.Jar.

**Comment by VictorMarty** [comment]
[Gradle 8 does no longer allow classifier inside Jar task. archiveClassifier must be used instead.](https://stackoverflow.com/questions/75660848/could-not-set-unknown-property-classifier-for-task-idl-parsersourcejar-of)

this lines in build.gradle failed build:
      classifier = 'javadoc'
      classifier = 'sources'

for me help [downgrade gradle to 7.6.4](https://stackoverflow.com/questions/33892760/how-to-downgrade-to-older-version-of-gradle).

**Comment by GennadySX** [comment]
https://github.com/appmetrica/appmetrica-react-native-plugin

Now appmetrica released a new version and moved to another repo.

Please follow link above and update asap for performance your app.
